### PR TITLE
changed type of message to STATUS to be printed to sysout

### PR DESCRIPTION
**Pull request by PhilippvK**
Without `STATUS` the message won't be printed to sys out, hence can not be piped into a file using `cmake .. > log.txt`

Nothing important.

### CODE REVIEW

**Comment by alxhoff** [comment]
Does this mean the board arrived?

**Comment by PhilippvK** [comment]
I have been to lazy to go downstairs (5 floors!) to check the mailbox.

But the toolchain is working as well as building. I will give you an update on flashing ans debugging tomorrow (if the board arrives). Do i have to test any specific behavior/application?

**Comment by alxhoff** [comment]
hahahaa nah, just see if you can change the LED period or something and flash and debug it. Should be pretty straight forward, which is the key as all online methods I came across are so unnecessarily complex.

**Comment by PhilippvK** [comment]
@alxhoff it arrived today! many thanks....

Do I have to program it via the Micro USB port or via stlink/jtag?

**Comment by PhilippvK** [comment]
Oh, I should have taken a look at your README, first.

So, next question. Do I have to use a stlink or is the jlink you send me fine, too?

**Comment by alxhoff** [comment]
Both should work. I use a st-link. You'll need to change to openocd stuff if you use a jlink as the programming dev

**Pull request merged**
